# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5124a4de614b0913e17082cea40d11457f5b3b0362582b3b527abc1c384f92e50f80da23ffa006535e9a206784dba746938bdeceb4daaea76b328a165651e64

test:
  secret_key_base: fceff75e4045ce2f0b068daae124cf5debd9de9dcc8fc893b987d40c8904dc618defc4f5abe4b7223104f095c6a4180ff46c19aaa12bfc7ca2babb372ba76be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
